window.COURSE_DATA = {
  course: 'Técnico em Redes de Computadores',
  ucs: [
    { id:'UC1', nome:'Fundamentos de redes de computadores', competencia:'Compreender fundamentos, topologias, dispositivos e modelos de referência de redes.', habilidades:['Identificar componentes físicos e lógicos de uma rede','Relacionar topologias de rede a cenários de uso','Interpretar o modelo OSI e TCP/IP em situações práticas'], conhecimentos:['Topologias LAN','Modelo OSI','Modelo TCP/IP','Dispositivos de rede'], normas:['Não se aplica','Boas práticas de documentação']},
    { id:'UC2', nome:'Endereçamento e serviços de rede', competencia:'Configurar endereçamento IP e serviços básicos de rede.', habilidades:['Planejar endereçamento IPv4 em sub-redes','Configurar serviços básicos de rede','Validar conectividade lógica entre hosts'], conhecimentos:['IPv4','Máscara de sub-rede','DHCP','DNS'], normas:['Não se aplica']},
    { id:'UC3', nome:'Switching e VLAN', competencia:'Configurar redes locais com comutação, segmentação e documentação técnica.', habilidades:['Configurar VLANs em switches gerenciáveis','Validar trunk e portas de acesso','Documentar segmentação lógica da rede'], conhecimentos:['VLAN','Trunk','Switch gerenciável','Tabela MAC'], normas:['Boas práticas de documentação']},
    { id:'UC4', nome:'Roteamento básico', competencia:'Implementar roteamento entre redes locais.', habilidades:['Configurar roteamento estático','Validar comunicação entre sub-redes','Identificar falhas de gateway e rotas'], conhecimentos:['Roteamento estático','Gateway padrão','Tabela de rotas'], normas:['Não se aplica']},
    { id:'UC5', nome:'Wi‑Fi e mobilidade', competencia:'Implementar redes sem fio com critérios de cobertura e segurança.', habilidades:['Selecionar padrão Wi‑Fi adequado ao cenário','Planejar cobertura e SSID','Aplicar segurança básica em WLAN'], conhecimentos:['802.11','SSID','WPA2/WPA3','Cobertura'], normas:['Boas práticas de instalação']},
    { id:'UC6', nome:'Segurança básica em redes', competencia:'Aplicar controles básicos de segurança em infraestrutura de redes.', habilidades:['Identificar riscos básicos em rede local','Aplicar segmentação e boas práticas','Documentar medidas preventivas'], conhecimentos:['ACL','Segmentação','Segurança física','Privilégios'], normas:['Política de segurança interna']},
    { id:'UC7', nome:'Implementar cabeamento estruturado e telefonia IP', competencia:'Implementar infraestrutura de cabeamento estruturado e soluções de telefonia IP em redes corporativas.', habilidades:['Interpretar projetos de cabeamento estruturado para redes de computadores','Planejar a infraestrutura física da rede (racks, patch panels, canaletas, eletrocalhas)','Identificar e selecionar cabos e conectores adequados (UTP, STP, fibra óptica, RJ-45)','Executar montagem e conectorização de cabos de rede (crimpagem)','Instalar pontos de rede, patch panels e racks','Organizar e realizar gerenciamento de cabos (cable management)','Executar testes de certificação e continuidade do cabeamento','Realizar manutenção preventiva e corretiva em cabeamento estruturado','Configurar e instalar telefonia IP (VoIP)','Integrar telefonia IP à infraestrutura de rede existente','Configurar dispositivos de comunicação VoIP (softphones, telefones IP, ATA, PABX IP)','Realizar testes de funcionamento e qualidade de serviço (QoS) em telefonia IP','Elaborar documentação técnica da infraestrutura de rede'], conhecimentos:['Conceito de cabeamento estruturado','Norma TIA/EIA-568','Norma TIA-569','Norma TIA-606','Subsistemas do cabeamento estruturado','Cabeamento horizontal','Backbone','Área de trabalho','Sala de equipamentos','Entrada de serviços','Cabos UTP','Cabos STP','Cabos FTP','Fibra óptica','Categorias Cat5e','Categorias Cat6','Categorias Cat6a','Conector RJ-45','Keystone','Patch cord','Racks','Patch panels','Organizadores de cabos','Topologias LAN','Ferramentas de crimpagem','Punch down','Testadores de cabos','VoIP','Arquitetura de PABX IP','SIP','RTP','H.323','Telefones IP','Gateways ATA','Softphones','QoS para voz','Integração voz e dados','Segurança básica em VoIP'], normas:['TIA/EIA-568','TIA-569','TIA-606','Boas práticas de documentação','QoS corporativo']},
    { id:'UC8', nome:'Documentação e suporte', competencia:'Registrar tecnicamente a infraestrutura e prestar suporte básico ao ambiente de redes.', habilidades:['Elaborar documentação técnica de rede','Registrar ocorrências e evidências','Organizar inventário de ativos de rede'], conhecimentos:['Inventário','Topologia lógica','Topologia física','Registro técnico'], normas:['Boas práticas de documentação']}
  ]
};
